### ISSUE TITLE
highlight not working 

### ISSUE THREAD

**Issue by cocobear** [kristijanhusak/defx-icons#11]
When I enable hightlight in vimrc, and enable defx, it happened:
`g:defx_icons_enable_syntax_highlight`

> Error invoking '_defx_start' on channel 5 (python3-rplugin-host):
> error caught in request handler '_defx_start [[['/Users/cocobear/'], {'columns': 'git:ident:icons:filename:type', 'auto_cd': 0, 'prev_bufnr': 1, 'root_marker': '\ufb0c ', 'resume': 1, 'auto_recursive_level'
> : 0, 'sort': 'filename', 'listed': 0, 'new': 0, 'ignored_files': '.*', 'direction': 'topleft', 'visual_end': 0, 'winheight': 30, 'profile': 0, 'search': '/Users/cocobear/abc', 'buffer_name': 'default', 'win
> width': 35, 'split': 'vertical', 'visual_start': 0, 'cursor': 1, 'winrelative': 'editor', 'prev_winid': 1000, 'wincol': 51, 'winrow': 16, 'session_file': '', 'show_ignored_files': 1, 'drives': [], 'toggle':
>  1}]]':
> Traceback (most recent call last):
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/__init__.py", line 36, in start
>     self._rplugin.start(args)
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/rplugin.py", line 32, in start
>     views[0].init(paths, context, self._clipboard)
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 51, in init
>     if not self._init_defx(paths, clipboard):
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 382, in _init_defx
>     self.redraw(True)
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 141, in redraw
>     self._init_column_syntax()
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/view.py", line 538, in _init_column_syntax
>     source_highlights = column.highlight_commands()
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/column/icons.py", line 121, in highlight_commands
>     commands += self.syn_list('exact_matches')
>   File "/Users/cocobear/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/defx/column/icons.py", line 101, in syn_list
>     self.syntax_name, text, opts['color'], opts.get('term_color',
> KeyError: 'color'

I try to print  opts var :
```
        with open('/Users/cocobear/vimlog','a') as f:
            f.write(str(self.opts))
            f.write('\n\n')
```
it is :

`{'extensions': {'erl': {'term_color': 103, 'icon': '\ue7b1', 'color': '834F79'}, 'styl': {'term_color': 65, 'icon': '\ue600', 'color': '8FAA54'}, 'rmd': {'term_color': 231, 'icon': '\ue609', 'color': 'FFFFFF'}, 'pyc': {'term_color': 229, 'icon': '\ue606', 'color': 'F09F17'}, 'pyd': {'term_color': 229, 'icon': '\ue606', 'color': 'F09F17'}, 'go': {'term_color': 137, 'icon': '\ue627', 'color': 'F5C06F'}, 'suo': {'term_color': 60, 'icon': '\ue70c', 'color': '834F79'}, 'lua': {'term_color': 60, 'icon': '\ue620', 'color': '834F79'}, 'bash': {'term_color': 231, 'icon': '\ue795', 'color': 'FFFFFF'}, 'pyo': {'term_color': 229, 'icon': '\ue606', 'color': 'F09F17'}, 'mustache': {'term_color': 208, 'icon': '\ue60f', 'color': 'D4843E'}, 'gif': {'term_color': 66, 'icon': '\ue60d', 'color': '3AFFDB'}, 'diff': {'term_color': 231, 'icon': '\ue728', 'color': 'FFFFFF'}, 'fs': {'term_color': 67, 'icon': '\ue7a7', 'color': '689FB6'}, 'java': {'term_color': 60, 'icon': '\ue738', 'color': '834F79'}, 'lhs': {'term_color': 137, 'icon': '\ue61f', 'color': 'F5C06F'}, 'scala': {'term_color': 131, 'icon': '\ue737', 'color': 'AE403F'}, 'zsh': {'term_color': 231, 'icon': '\ue795', 'color': 'FFFFFF'}, 'jpeg': {'term_color': 66, 'icon': '\ue60d', 'color': '3AFFDB'}, 'ts': {'term_color': 67, 'icon': '\ue628', 'color': '689FB6'}, 'fsi': {'term_color': 67, 'icon': '\ue7a7', 'color': '689FB6'}, 'vim': {'term_color': 65, 'icon': '\ue62b', 'color': '8FAA54'}, 'scss': {'term_color': 205, 'icon': '\ue603', 'color': 'CB6F6F'}, 'js': {'term_color': 137, 'icon': '\ue60c', 'color': 'F5C06F'}, 'gitcommit': {'icon': '\uf113'}, 'xul': {'term_color': 166, 'icon': '\ue745', 'color': 'F16529'}, 'R': {'icon': 'ﳒ'}, 'fish': {'term_color': 65, 'icon': '\ue795', 'color': '8FAA54'}, 'htm': {'term_color': 166, 'icon': '\ue60e', 'color': 'F16529'}, 'rb': {'term_color': 131, 'icon': '\ue791', 'color': 'AE403F'}, 'c': {'term_color': 67, 'icon': '\ue61e', 'color': '689FB6'}, 'd': {'term_color': 131, 'icon': '\ue7af', 'color': 'AE403F'}, 'md': {'term_color': 229, 'icon': '\ue609', 'color': 'F09F17'}, 'h': {'term_color': 231, 'icon': '\uf0fd', 'color': 'FFFFFF'}, 'mli': {'term_color': 229, 'icon': 'λ', 'color': 'F09F17'}, 'ml': {'term_color': 229, 'icon': 'λ', 'color': 'F09F17'}, 'css': {'term_color': 67, 'icon': '\ue614', 'color': '689FB6'}, 'jpg': {'term_color': 66, 'icon': '\ue60d', 'color': '3AFFDB'}, 'cc': {'term_color': 67, 'icon': '\ue61d', 'color': '689FB6'}, 't': {'term_color': 67, 'icon': '\ue769', 'color': '689FB6'}, 'jl': {'term_color': 60, 'icon': '\ue624', 'color': '834F79'}, 'cljc': {'term_color': 65, 'icon': '\ue768', 'color': '8FAA54'}, 'ksh': {'term_color': 231, 'icon': '\ue795', 'color': 'FFFFFF'}, 'hs': {'term_color': 137, 'icon': '\ue61f', 'color': 'F5C06F'}, 'sql': {'term_color': 57, 'icon': '\ue706', 'color': '44788E'}, 'tsx': {'term_color': 231, 'icon': '\ue7ba', 'color': 'FFFFFF'}, 'cp': {'term_color': 67, 'icon': '\ue61d', 'color': '689FB6'}, 'ps1': {'term_color': 231, 'icon': '\ue795', 'color': 'FFFFFF'}, 'bmp': {'term_color': 66, 'icon': '\ue60d', 'color': '3AFFDB'}, 'sln': {'term_color': 60, 'icon': '\ue70c', 'color': '834F79'}, 'cljs': {'term_color': 65, 'icon': '\ue76a', 'color': '8FAA54'}, 'html': {'term_color': 166, 'icon': '\ue60e', 'color': 'F16529'}, 'cpp': {'term_color': 67, 'icon': '\ue61d', 'color': '689FB6'}, 'hrl': {'term_color': 205, 'icon': '\ue7b1', 'color': 'CB6F6F'}, 'rs': {'term_color': 166, 'icon': '\ue7a8', 'color': 'F16529'}, 'sass': {'term_color': 231, 'icon': '\ue603', 'color': 'FFFFFF'}, 'vue': {'term_color': 65, 'icon': '\ufd42', 'color': '8FAA54'}, 'rlib': {'term_color': 166, 'icon': '\ue7a8', 'color': 'F16529'}, 'awk': {'term_color': 231, 'icon': '\ue795', 'color': 'FFFFFF'}, 'conf': {'term_color': 231, 'icon': '\ue615', 'color': 'FFFFFF'}, 'pl': {'term_color': 67, 'icon': '\ue769', 'color': '689FB6'}, 'pm': {'term_color': 67, 'icon': '\ue769', 'color': '689FB6'}, 'hbs': {'term_color': 208, 'icon': '\ue60f', 'color': 'D4843E'}, 'pp': {'term_color': 231, 'icon': '\uf499', 'color': 'FFFFFF'}, 'tex': {'icon': '\uf18d'}, 'py': {'term_color': 229, 'icon': '\ue606', 'color': 'F09F17'}, 'fsscript': {'term_color': 67, 'icon': '\ue7a7', 'color': '689FB6'}, 'less': {'term_color': 57, 'icon': '\ue614', 'color': '44788E'}, 'r': {'icon': 'ﳒ'}, 'ai': {'term_color': 166, 'icon': '\ue7b4', 'color': 'F16529'}, 'jsx': {'term_color': 67, 'icon': '\ue7ba', 'color': '689FB6'}, 'csh': {'term_color': 231, 'icon': '\ue795', 'color': 'FFFFFF'}, 'psd': {'term_color': 57, 'icon': '\ue7b8', 'color': '44788E'}, 'psb': {'term_color': 57, 'icon': '\ue7b8', 'color': '44788E'}, 'json': {'term_color': 137, 'icon': '\ue60b', 'color': 'F5C06F'}, 'rss': {'term_color': 166, 'icon': '\ue619', 'color': 'F16529'}, 'cxx': {'term_color': 67, 'icon': '\ue61d', 'color': '689FB6'}, 'png': {'term_color': 66, 'icon': '\ue60d', 'color': '3AFFDB'}, 'sh': {'term_color': 103, 'icon': '\ue795', 'color': '834F79'}, 'hpp': {'term_color': 231, 'icon': '\uf0fd', 'color': 'FFFFFF'}, 'pdf': {'icon': '\uf1c1'}, 'bat': {'term_color': 231, 'icon': '\ue615', 'color': 'FFFFFF'}, 'fsx': {'term_color': 67, 'icon': '\ue7a7', 'color': '689FB6'}, 'ini': {'term_color': 231, 'icon': '\ue615', 'color': 'FFFFFF'}, 'markdown': {'term_color': 229, 'icon': '\ue609', 'color': 'F09F17'}, 'db': {'term_color': 67, 'icon': '\ue706', 'color': '689FB6'}, 'twig': {'term_color': 65, 'icon': '\ue61c', 'color': '8FAA54'}, 'yaml': {'term_color': 231, 'icon': '\ue615', 'color': 'FFFFFF'}, 'coffee': {'term_color': 130, 'icon': '\ue61b', 'color': '905532'}, 'bib': {'icon': '\uf19c'}, 'ejs': {'term_color': 229, 'icon': '\ue60e', 'color': 'F09F17'}, 'dart': {'term_color': 231, 'icon': '\ue798', 'color': 'FFFFFF'}, 'edn': {'term_color': 65, 'icon': '\ue76a', 'color': '8FAA54'}, 'slim': {'term_color': 208, 'icon': '\ue60e', 'color': 'D4843E'}, 'clj': {'term_color': 65, 'icon': '\ue768', 'color': '8FAA54'}, 'dump': {'term_color': 67, 'icon': '\ue706', 'color': '689FB6'}, 'hxx': {'term_color': 231, 'icon': '\uf0fd', 'color': 'FFFFFF'}, 'php': {'term_color': 60, 'icon': '\ue608', 'color': '834F79'}, 'ico': {'term_color': 66, 'icon': '\ue60d', 'color': '3AFFDB'}, 'yml': {'term_color': 231, 'icon': '\ue615', 'color': 'FFFFFF'}}, 'directory_icon': '\ue5ff', 'parent_icon': '\ue5fe', 'mark_icon': '*', 'enable_syntax_highlight': 1, 'exact_matches': {'.vimrc': {'term_color': 231, 'icon': '\ue62b', 'color': 'FFFFFF'}, 'gruntfile.coffee': {'term_color': 229, 'icon': '\ue611', 'color': 'F09F17'}, 'bash_profile': {'icon': '\ue795'}, '_gvimrc': {'term_color': 231, 'icon': '\ue62b', 'color': 'FFFFFF'}, '_vimrc': {'term_color': 231, 'icon': '\ue62b', 'color': 'FFFFFF'}, 'dropbox': {'term_color': 231, 'icon': '\ue707', 'color': 'FFFFFF'}, '.gvimrc': {'term_color': 231, 'icon': '\ue62b', 'color': 'FFFFFF'}, 'license': {'term_color': 231, 'icon': '\ue60a', 'color': 'FFFFFF'}, 'procfile': {'term_color': 60, 'icon': '\ue607', 'color': '834F79'}, '.bash_profile': {'icon': '\ue795'}, '.gitignore': {'icon': '\uf113'}, 'gruntfile.js': {'term_color': 229, 'icon': '\ue611', 'color': 'F09F17'}, '.bashrc': {'icon': '\ue795'}, '.bashprofile': {'term_color': 231, 'icon': '\ue615', 'color': 'FFFFFF'}, 'gulpfile.coffee': {'term_color': 205, 'icon': '\ue610', 'color': 'CB6F6F'}, 'gruntfile.ls': {'term_color': 229, 'icon': '\ue611', 'color': 'F09F17'}, 'node_modules': {'term_color': 65, 'icon': '\ue718', 'color': '8FAA54'}, 'gulpfile.js': {'term_color': 205, 'icon': '\ue610', 'color': 'CB6F6F'}, 'bashrc': {'icon': '\ue795'}, '.zshrc': {'term_color': 231, 'icon': '\ue615', 'color': 'FFFFFF'}, 'gulpfile.ls': {'term_color': 205, 'icon': '\ue610', 'color': 'CB6F6F'}, 'docker-compose.yml': {'term_color': 229, 'icon': '\ue7b0', 'color': 'F09F17'}, '.gitconfig': {'icon': '\uf113'}, '.ds_store': {'term_color': 231, 'icon': '\ue615', 'color': 'FFFFFF'}, 'react.jsx': {'term_color': 67, 'icon': '\ue625', 'color': '689FB6'}, 'dockerfile': {'term_color': 67, 'icon': '\ue7b0', 'color': '689FB6'}, 'favicon.ico': {'term_color': 229, 'icon': '\ue623', 'color': 'F09F17'}}, 'nested_closed_tree_icon': '\ue5ff', 'column_length': 2, 'default_icon': '\ue612', 'nested_opened_tree_icon': '\ue5fe', 'exact_dir_matches': {'Templates': {'icon': '\uf0c5'}, 'Dropbox': {'icon': '\ue707'}, 'Pictures': {'icon': '\ue244'}, 'Documents': {'icon': '\uf401'}, '.git': {'icon': '\ue5fb'}, 'Music': {'icon': '\uf025'}, 'Public': {'icon': '\uf42b'}, 'Downloads': {'icon': '\uf498'}, 'Videos': {'icon': '\uf447'}, 'Desktop': {'icon': '\uf108'}}, 'root_opened_tree_icon': '\ue5fe', 'pattern_matches': {'.*angular.*\\.js$': {'term_color': 131, 'icon': '\ue753', 'color': 'AE403F'}, '.*materialize.*\\.css$': {'term_color': 209, 'icon': '\ue7b6', 'color': 'EE6E73'}, '.*jquery.*\\.js$': {'term_color': 67, 'icon': '\ue750', 'color': '689FB6'}, '.*backbone.*\\.js$': {'term_color': 57, 'icon': '\ue752', 'color': '44788E'}, '.*vimrc.*': {'term_color': 231, 'icon': '\ue62b', 'color': 'FFFFFF'}, '.*materialize.*\\.js$': {'term_color': 209, 'icon': '\ue7b6', 'color': 'EE6E73'}, '.*mootools.*\\.js$': {'term_color': 231, 'icon': '\ue78f', 'color': 'FFFFFF'}, '.*require.*\\.js$': {'term_color': 67, 'icon': '\ue770', 'color': '689FB6'}, 'Vagrantfile$': {'term_color': 231, 'icon': '\uf2b8', 'color': 'FFFFFF'}}, 'directory_symlink_icon': '\uf482'}
`

some of it does not contins color , like 
`'.bash_profile': {'icon': '\ue795'}`
I think something wrong when load this vars from config file

**Comment by cocobear** [comment]
I found it is config problem of my vimrc. I remove `"let g:defx_icons_exact_matches = {
"            \ '.gitconfig': {'icon': ''},
"            \ '.gitignore': {'icon':''},
"            \ 'bashrc': {'icon': ''},
"            \ '.bashrc': {'icon': ''},
"            \ 'bash_profile': {'icon':''},
"            \ '.bash_profile': {'icon':''},
"            \ }
            \ }
`
now it worked .
sorry for the bother.
